### ISSUE TITLE
25.2.4. 系统状态比对有一处文本格式貌似有些问题

### ISSUE THREAD

**Issue by Tongzp** [FreeBSD-Ask/Handbook#107]
![image](https://github.com/FreeBSD-Ask/Handbook/assets/33510725/044ea639-9e4f-47e8-aeb4-293fb58bfef8)

此处的IDS是否需要与前面 freebsd-update 在同一个代码块格式里呢

**Comment by ykla** [comment]
已经改正。感谢。
