### ISSUE TITLE
第 3.3.2 节：——表格显示异常

### ISSUE THREAD

**Issue by bduath** [FreeBSD-Ask/Handbook#133]
**英文原文章节**

>>## 3.3.2. User Accounts

**表格显示异常**
![图片](https://github.com/user-attachments/assets/f7442908-b78f-42e0-aed5-366ff952a9c7)
![图片](https://github.com/user-attachments/assets/381b0501-469f-4b9f-89de-b0ac22347cb3)

**Comment by ykla** [comment]
目前不做处理，待重译。如有需要，可以 PR。
